In [1]:
!pip install pandas --q

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("titanic_train.csv")

In [5]:
df

,passenger_id,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,survived
0,1216,3,"Smyth, Miss. Julia",female,NaN,0,0,335432,7.7333,NaN,Q,13,NaN,NaN,1
1,699,3,"Cacic, Mr. Luka",male,38.0,0,0,315089,8.6625,NaN,S,NaN,NaN,Croatia,0
2,1267,3,"Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...",female,30.0,1,1,345773,24.1500,NaN,S,NaN,NaN,NaN,0
3,449,2,"Hocking, Mrs. Elizabeth (Eliza Needs)",female,54.0,1,3,29105,23.0000,NaN,S,4,NaN,"Cornwall / Akron, OH",1
4,576,2,"Veal, Mr. James",male,40.0,0,0,28221,13.0000,NaN,S,NaN,NaN,"Barre, Co Washington, VT",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,158,1,"Hipkins, Mr. William Edward",male,55.0,0,0,680,50.0000,C39,S,NaN,NaN,London / Birmingham,0
846,174,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,B37,C,NaN,258.0,"Buffalo, NY",0
847,467,2,"Kantor, Mrs. Sinai (Miriam Sternin)",female,24.0,1,0,244367,26.0000,NaN,S,12,NaN,"Moscow / Bronx, NY",1
848,1112,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,NaN,NaN,NaN,0
849,425,2,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,13.0000,NaN,S,NaN,19.0,"Bronx, NY",0

In [6]:
df.head(2)
df.tail()
df.sample(5)

,passenger_id,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,survived
546,52,1,"Carrau, Mr. Francisco M",male,28.0,0,0,113059,47.10,NaN,S,NaN,NaN,"Montevideo, Uruguay",0
691,859,3,"Hegarty, Miss. Hanora ""Nora""",female,18.0,0,0,365226,6.75,NaN,Q,NaN,NaN,NaN,0
719,314,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.0,1,1,113503,211.50,C80,C,4,NaN,"Elkins Park, PA",1
49,330,2,"Ashby, Mr. John",male,57.0,0,0,244346,13.00,NaN,S,NaN,NaN,"West Hoboken, NJ",0
13,446,2,"Hocking, Miss. Ellen ""Nellie""",female,20.0,2,1,29105,23.00,NaN,S,4,NaN,"Cornwall / Akron, OH",1

In [7]:
len(df.columns)
len(df)

850

In [8]:
df.shape # row, colums

(850, 15)

In [9]:
type(df['age'])

pandas.core.series.Series

In [10]:
type(df[['age']])

pandas.core.frame.DataFrame

In [11]:
df['age']

0       NaN
1      38.0
2      30.0
3      54.0
4      40.0
       ...
845    55.0
846    58.0
847    24.0
848     3.0
849    52.0
Name: age, Length: 850, dtype: float64

In [12]:
df['age'].isnull().sum()

np.int64(174)

In [13]:
df['age'] = df['age'].fillna(df['age'].mean())

df['age'] = df['age'].fillna(df['age'].median())
df['age'] = df['age'].fillna(df['age'].mode())
df['age'] = df['age'].fillna(df['age'].min())
df['age'] = df['age'].fillna(df['age'].max())

In [14]:
df['age'].isnull().sum()

np.int64(0)

In [15]:
df.columns

Index(['passenger_id', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest',
       'survived'],
      dtype='object')

In [16]:
# df = df.drop("name",axis=1)

df.drop("name",axis=1,inplace=True)

In [17]:
len(df.columns)

14

In [18]:
df.describe()

,passenger_id,pclass,age,sibsp,parch,fare,body,survived
count,850.000000,850.00000,850.000000,850.000000,850.000000,849.000000,73.000000,850.000000
mean,662.816471,2.32000,29.519847,0.522353,0.382353,34.012701,165.821918,0.368235
std,380.751936,0.83853,12.984533,1.112132,0.879511,53.705779,99.068487,0.482610
min,1.000000,1.00000,0.166700,0.000000,0.000000,0.000000,4.000000,0.000000
25%,332.250000,2.00000,22.000000,0.000000,0.000000,7.895800,75.000000,0.000000
50%,676.500000,3.00000,29.519847,0.000000,0.000000,14.108300,166.000000,0.000000
75%,992.250000,3.00000,34.875000,1.000000,0.000000,31.000000,260.000000,1.000000
max,1307.000000,3.00000,80.000000,8.000000,9.000000,512.329200,328.000000,1.000000

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   passenger_id  850 non-null    int64
 1   pclass        850 non-null    int64
 2   sex           850 non-null    object
 3   age           850 non-null    float64
 4   sibsp         850 non-null    int64
 5   parch         850 non-null    int64
 6   ticket        850 non-null    object
 7   fare          849 non-null    float64
 8   cabin         191 non-null    object
 9   embarked      849 non-null    object
 10  boat          308 non-null    object
 11  body          73 non-null     float64
 12  home.dest     464 non-null    object
 13  survived      850 non-null    int64
dtypes: float64(3), int64(5), object(6)
memory usage: 93.1+ KB

In [20]:
df['age'] = (df['age'] - df['age'].min())/(df['age'].max()-df['age'].min())

In [21]:
sum(df['age']>=1)

1

In [22]:
df[df['age']==df['age'].max()]['cabin']

177    A23
Name: cabin, dtype: object

In [23]:
df['age'] = (df['age'] - df['age'].mean())/(df['age'].std())

In [ ]:
# df['age'].std()
# df['age'].mean()

np.float64(-1.8599501024308505e-16)

# Encoding ...

In [26]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\Rahi\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in C:\Users\Rahi\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.3.3)
Requirement already satisfied: scipy>=1.8.0 in C:\Users\Rahi\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\Rahi\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\Rahi\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [27]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [28]:
le = LabelEncoder()
oe = OrdinalEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['sex'] = oe.fit_transform(df[['sex']])

In [29]:
df['sex']

0      0.0
1      1.0
2      0.0
3      0.0
4      1.0
      ...
845    1.0
846    1.0
847    0.0
848    0.0
849    1.0
Name: sex, Length: 850, dtype: float64

In [30]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
ohe.fit_transform(df[['sex']]).toarray()
ohe.get_feature_names_out()
ohe_df = pd.DataFrame(
    ohe.fit_transform(df[['sex']]).toarray(),
    columns=ohe.get_feature_names_out()
)
df = pd.concat([df,ohe_df],axis=1)
df

,passenger_id,pclass,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,survived,sex_0.0,sex_1.0
0,1216,3,0.0,0.000000,0,0,335432,7.7333,NaN,Q,13,NaN,NaN,1,1.0,0.0
1,699,3,1.0,0.653096,0,0,315089,8.6625,NaN,S,NaN,NaN,Croatia,0,0.0,1.0
2,1267,3,0.0,0.036979,1,1,345773,24.1500,NaN,S,NaN,NaN,NaN,0,1.0,0.0
3,449,2,0.0,1.885332,1,3,29105,23.0000,NaN,S,4,NaN,"Cornwall / Akron, OH",1,1.0,0.0
4,576,2,1.0,0.807126,0,0,28221,13.0000,NaN,S,NaN,NaN,"Barre, Co Washington, VT",0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,158,1,1.0,1.962347,0,0,680,50.0000,C39,S,NaN,NaN,London / Birmingham,0,0.0,1.0
846,174,1,1.0,2.193391,0,0,11771,29.7000,B37,C,NaN,258.0,"Buffalo, NY",0,0.0,1.0
847,467,2,0.0,-0.425109,1,0,244367,26.0000,NaN,S,12,NaN,"Moscow / Bronx, NY",1,1.0,0.0
848,1112,3,0.0,-2.042418,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,NaN,NaN,NaN,0,1.0,0.0
849,425,2,1.0,1.731302,0,0,250647,13.0000,NaN,S,NaN,19.0,"Bronx, NY",0,0.0,1.0

In [31]:
df.head()

,passenger_id,pclass,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,survived,sex_0.0,sex_1.0
0,1216,3,0.0,0.000000,0,0,335432,7.7333,NaN,Q,13,NaN,NaN,1,1.0,0.0
1,699,3,1.0,0.653096,0,0,315089,8.6625,NaN,S,NaN,NaN,Croatia,0,0.0,1.0
2,1267,3,0.0,0.036979,1,1,345773,24.1500,NaN,S,NaN,NaN,NaN,0,1.0,0.0
3,449,2,0.0,1.885332,1,3,29105,23.0000,NaN,S,4,NaN,"Cornwall / Akron, OH",1,1.0,0.0
4,576,2,1.0,0.807126,0,0,28221,13.0000,NaN,S,NaN,NaN,"Barre, Co Washington, VT",0,0.0,1.0

In [32]:
df = df[['pclass','sex']]

In [33]:
df

     pclass  sex
0         3  0.0
1         3  1.0
2         3  0.0
3         2  0.0
4         2  1.0
..      ...  ...
845       1  1.0
846       1  1.0
847       2  0.0
848       3  0.0
849       2  1.0

[850 rows x 2 columns]

In [34]:
df = pd.get_dummies(df,dtype=int)

In [35]:
df

     pclass  sex
0         3  0.0
1         3  1.0
2         3  0.0
3         2  0.0
4         2  1.0
..      ...  ...
845       1  1.0
846       1  1.0
847       2  0.0
848       3  0.0
849       2  1.0

[850 rows x 2 columns]